name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t dvwa:latest .

  sca-owasp:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install unzip and curl
        run: sudo apt-get update && sudo apt-get install unzip curl -y

      - name: Download OWASP Dependency Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check.zip -d .
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --project "DVWA" \
            --scan ./dvwa \
            --format "HTML" \
            --out ./dependency-check-report \
            --failOnCVSS 7 || true

      - name: Upload OWASP report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report

